# Match resolver with nixos-unstable haskellPackages
resolver: lts-19.25
packages:
- cachix
- cachix-api
extra-deps:
- hercules-ci-cnix-store-0.3.3.1
- cabal-pkg-config-version-hook-0.1.0.0
- nix-narinfo-0.1.0.1
- hnix-store-core-0.6.0.0
nix:
  enable: true
  shell-file: ./nix/stack-shell.nix
