# Match resolver with nixos-unstable haskellPackages
resolver: lts-21.11
packages:
- cachix
- cachix-api
extra-deps:
- hercules-ci-cnix-store-0.3.4.0
- cabal-pkg-config-version-hook-0.1.0.0
- nix-narinfo-0.1.0.1
- fsnotify-0.4.1.0
- hnix-store-core-0.6.1.0
- algebraic-graphs-0.6.1
- saltine-0.2.0.1
nix:
  enable: true
  pure: false
  shell-file: ./shell.nix
