resolver: nightly-2022-09-22
packages:
- cachix
- cachix-api
extra-deps:
- hercules-ci-cnix-store-0.3.3.1
- nix-narinfo-0.1.0.1
- cabal-pkg-config-version-hook-0.1.0.0
allow-newer: false
nix:
  enable: true
  shell-file: ./nix/stack-shell.nix
