resolver: nightly-2022-06-20
packages:
- cachix-api
- cachix
extra-deps:
- hercules-ci-cnix-store-0.3.3.0
- netrc-0.2.0.0
- nix-narinfo-0.1.0.1
- protolude-0.3.2
- servant-auth-swagger-0.2.10.1
- cabal-pkg-config-version-hook-0.1.0.0
# https://github.com/haskell-hvr/netrc/issues/5
allow-newer: true
nix:
  packages: []
  shell-file: ./nix/stack-shell.nix
