name:                cachix
version:             0.1.1
github:              "cachix/cachix"
license:             Apache-2.0
author:              "Domen Kožar"
maintainer:          "domen@enlambda.com"
copyright:           "2018 Domen Kožar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Command line client for Nix binary cache hosting https://cachix.org

dependencies:
- async
- base >= 4.7 && < 5
- base16-bytestring
- base64-bytestring
- bifunctors
- bytestring
- cachix-api
- conduit >= 1.3.0
- conduit-extra
- cookie
- cryptonite
- dhall
- directory
- ed25519
- here
- http-client-tls
- http-client
- http-conduit
- http-types
- lzma-conduit
- megaparsec
- memory
- mmorph
- fsnotify
- optparse-applicative
- process
- protolude
- resourcet
- servant >= 0.14.1
- servant-auth
- servant-auth-client >= 0.3.3.0
- servant-client >= 0.14
- servant-client-core >= 0.14.1
- servant-streaming-client >= 0.3.0.0
- streaming
- text
- uri-bytestring
- unix
- versions

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- RecordWildCards

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -fwarn-tabs
  -fwarn-unused-imports
  -fwarn-missing-signatures
  -fwarn-name-shadowing
  -fwarn-incomplete-patterns

library:
  source-dirs: src

executables:
  cachix:
    main:                Main.hs
    source-dirs:         cachix
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

tests:
  cachix-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cachix
    - hspec
    - protolude
