name: "Build"

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-13 # x86_64
          - macos-latest # macos-14 == aarch64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Make space
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo rm -rf /usr/local/lib/android || true
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - name: Setup read-only Cachix cache
      uses: cachix/cachix-action@master
      with:
        name: cachix
        skipPush: true

    - name: Build dev Cachix
      id: cachix
      run: |
        cachix_out=$(nix build .#cachix -L --show-trace --print-out-paths)
        echo "cachix_out=$cachix_out" >> "$GITHUB_OUTPUT"
        echo "cachix_bin=$cachix_out/bin/cachix" >> "$GITHUB_OUTPUT"

    - name: Cache dev build
      uses: cachix/cachix-action@master
      with:
        name: cachix
        cachixBin: '${{ steps.cachix.outputs.cachix_bin }}'
        pathsToPush: '${{ steps.cachix.outputs.cachix_out }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Setup Cachix cache with dev build
      uses: cachix/cachix-action@master
      with:
        name: cachix
        cachixBin: '${{ steps.cachix.outputs.cachix_bin }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - run: nix build -L '.#ci' '.#cachix' --show-trace --impure

    - name: "watch-exec test"
      env:
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      if: ${{ env.signingKey != '' }}
      run: ${{ steps.cachix.outputs.cachix_bin }} watch-exec cachix -- nix-build genpaths.nix --substituters 'https://cache.nixos.org'

    - name: "daemon watch-exec test"
      env:
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      if: ${{ env.signingKey != '' }}
      run: ${{ steps.cachix.outputs.cachix_bin }} daemon watch-exec cachix -- nix-build genpaths.nix --substituters 'https://cache.nixos.org'

  release:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
